Cover
ecvdbdx1617/github-for-fashion pull request #66
Opened 2017-05-05 09:01 UTC by matthieu-brillaxis

Update of cover.
Each user from cover.json can be use now, we just need to define how we will use them to load data for the homepage.
Should we create a fake repo on a github account with a json file ?

2017-05-09 09:31 UTC, DavidBruant commented
> Should we create a fake repo on a github account with a json file ?

No, we'll be using this repo. Please make a separate PR with a cover.json file listing real garment repos.

Is this PR ready to be merged?

2017-05-09 09:31 UTC, DavidBruant commented on src/components/pages/Home.vue
> +        let myJson = decodeURIComponent(escape(window.atob(file.data.content)));
ne need for `window.`

2017-05-09 09:32 UTC, DavidBruant commented on src/components/pages/Home.vue
> +        let myJson = decodeURIComponent(escape(window.atob(file.data.content)));
Unclear whether you need `decodeURIComponent` and `escape`

2017-05-09 09:33 UTC, DavidBruant commented on src/components/pages/Home.vue
> +        Object.keys(myJson).forEach((key) => {
By design, you already know the object has 2 keys and their names. No need to iterate over "all" keys

2017-05-09 09:33 UTC, DavidBruant commented on src/components/pages/Home.vue
> +              [user, repo] = String(myJson.secondary[secondaryKey]).split('/');
Why the `String` conversion?

2017-05-09 10:03 UTC, matthieu-brillaxis commented on src/components/pages/Home.vue
> +              [user, repo] = String(myJson.secondary[secondaryKey]).split('/');
If I don't do string conversion the .split() is not working like I want.

2017-05-09 10:11 UTC, matthieu-brillaxis commented
I prefer to wait before merging this PR. We can watch that at the next class. I will try to make changes before the next class since I know your comments.

2017-05-11 11:14 UTC, matthieu-brillaxis commented on src/components/pages/Home.vue
> +        let myJson = decodeURIComponent(escape(window.atob(file.data.content)));
Ok

2017-05-11 13:03 UTC, DavidBruant requested changes
LGTM otherwise

2017-05-11 13:03 UTC, DavidBruant commented on src/components/pages/Home.vue
> +        });
secundary missing

2017-05-11 13:03 UTC, DavidBruant commented on src/components/pages/Home.vue
> +        [user, repo] = String(myJson.primary).split('/');
string conversion?

2017-05-11 13:03 UTC, DavidBruant commented on src/components/pages/Home.vue
> +        /* eslint-disable no-unused-vars */
re-enable these rules

2017-06-08 13:01 UTC, merged